version: "3.8"
services:
  postgres:
    image: postgres:13.1-alpine
    container_name: kiwi-cc-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/dump.sql:/data/dump.sql
      - ./data/postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: redis:6.0-alpine
    container_name: kiwi-cc-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  server:
    build: ./server
    container_name: kiwi-cc-server
    ports:
      - "8100:8100"
    environment:
      DATABASE_URL: "postgresql://kiwi@postgres:5432/kiwi"
      REDIS_URL: "redis://redis:6379/0"

  webapp:
    build:
      context: ./webapp
      args:
        # API requests are done by user’s browser, so the base URL API URL
        # should belong to the network visible by the browser, not the
        # network created by docker-compose. For production deployment,
        # the image should be built with a real API URL like
        # https://api.kiwi.ki
        NEXT_PUBLIC_API_BASE_URL: "http://localhost:8100"
    container_name: kiwi-cc-webapp
    ports:
      - "8300:8300"
