
.PHONY: dev
dev:
	yarn next dev --port 8300

.PHONY: build
build:
	yarn next build

.PHONY: start
start:
	yarn next build

.PHONY: prettify
prettify:
	yarn prettier --write .

.PHONY: install_deps
install_deps:
	yarn
